import React from 'react'

function TServices() {
    return (
        <div className="min-h-screen bg-background text-foreground p-8 max-w-4xl mx-auto">
            <h1 className="text-4xl font-bold text-gradient mb-6">Terms of Service</h1>
            <p className="text-muted-foreground mb-6">Last Updated: 20-10-2025</p>

            <div className="space-y-8 text-muted-foreground leading-relaxed">
                <section>
                    <h2 className="text-2xl font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
                    <p>By accessing or using the LoveAI website and services ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to all of these Terms, do not use the Service.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold text-foreground mb-3">2. Eligibility (18+)</h2>
                    <p>You must be at least 18 years old or the age of legal majority in your jurisdiction to use our Service. By using the Service, you represent and warrant that you meet this age requirement. This Service is not intended for individuals under the age of 18.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold text-foreground mb-3">3. Description of Service</h2>
                    <p>LoveAI provides users with access to interactive AI companions for entertainment, companionship, and conversation. Users can chat with various AI personalities, some of whom are designed to engage in adult-themed, romantic, and "naughty" conversations.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold text-foreground mb-3">4. AI Companion Content Disclaimer</h2>
                    <p>You understand and agree to the following:</p>
                    <ul className="list-disc list-inside ml-4 space-y-2 mt-2">
                        <li><strong>Fictional Content:</strong> All AI companions are artificial, and their personalities and responses are computer-generated. They are not real people. Any and all content generated by the AI is fictional.</li>
                        <li><strong>For Entertainment Only:</strong> The Service is for entertainment and companionship purposes only. The AI companions cannot provide medical, legal, financial, or mental health advice. The Service is not a substitute for professional advice or real human relationships.</li>
                        <li><strong>Adult Themes:</strong> You acknowledge that you may encounter content (text and/or images) that could be considered adult, explicit, or "naughty." If you are sensitive to such content, you should not use the Service.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold text-foreground mb-3">5. User Accounts & Conduct</h2>
                    <p>You are responsible for safeguarding your account information. You agree not to:</p>
                    <ul className="list-disc list-inside ml-4 space-y-2 mt-2">
                        <li>Use the Service for any illegal or unauthorized purpose.</li>
                        <li>Attempt to solicit personal, identifying information from the AI.</li>
                        <li>Harass, abuse, or harm another person or our staff.</li>
                        <li>Attempt to reverse-engineer, "jailbreak," or discover the underlying code of the AI models.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold text-foreground mb-3">6. Payments and Subscriptions</h2>
                    <p>The Service may offer free and paid tiers. Some AI companions or features may be locked and require payment (e.g., "coins" or a subscription).</p>
                    <ul className="list-disc list-inside ml-4 space-y-2 mt-2">
                        <li>All payments are processed through our third-party payment processors.</li>
                        <li>[Clearly state your refund policy, e.g., "All purchases of coins and subscriptions are final and non-refundable."]</li>
                        <li>Prices and features are subject to change at any time.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold text-foreground mb-3">7. Termination</h2>
                    <p>We reserve the right to suspend or terminate your account at any time, without notice, for any reason, including for a breach of these Terms.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold text-foreground mb-3">8. Disclaimer of Warranties</h2>
                    <p>The Service is provided "AS IS" and "AS AVAILABLE" without any warranties of any kind. We do not warrant that the Service will be uninterrupted, secure, or error-free, or that the AI responses will always be coherent, accurate, or meet your expectations.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold text-foreground mb-3">9. Limitation of Liability</h2>
                    <p>To the fullest extent permitted by law, LoveAI (and its owners, employees, and affiliates) shall not be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with your use of the Service.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold text-foreground mb-3">10. Changes to Terms</h2>
                    <p>We may modify these Terms at any time. We will notify you by posting the updated Terms on this page. Your continued use of the Service after such changes constitutes your acceptance of the new Terms.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold text-foreground mb-3">11. Contact Us</h2>
                    <p>If you have any questions about these Terms, please contact us at sunraz1666@gmail.com.</p>
                </section>
            </div>
        </div>
    )
}

export default TServices